Metrics/LineLength:
  Max: 120

Metrics/MethodLength: 
  Max: 20

Metrics/ClassLength:
  Max: 200

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/migrate/*.rb'
    - 'db/*.rb'
    - 'bin/**/*'
